displayName=Shinigami Eyes
author=Kiwamari / GIM FatBwana
description=Enable your shinigami eyes to see peoples Gauntlet KC above their heads in the Gauntlet Lobby.
tags=Gauntlet,Shinigami eyes,Death Note,Kill Count,Corrupted Gauntlet
version=1
plugins=com.example.ShinigamiEyesPlugin
build=standard